pdf_path: "data/00_inputs"
queries:
  - What is the company's current ratio?
  - Estimate the intrinsic value of the company.
  - What risks are mentioned?
model: mistralai/mixtral-8x7b-instruct
top_k: 10